### ISSUE TITLE
Recent update throws an error

### ISSUE THREAD

**Issue by SudevKiyada** [vasturiano/three-spritetext#10]
With the recent update, am getting this error "this._text.split is not a function"

am calling as

```
variable.text = "value";
```

**Comment by vasturiano** [comment]
@SudevKiyada thanks for reaching out.

I'm unable to reproduce this error. Would you mind making a minimal replicating example on https://codepen.io/ ?

**Comment by HyeongHwanKim** [comment]
I saw an error, too.

global side ? error catch :  TypeError: this._text.split is not a function
    at _default._genCanvas (three-spritetext.module.js:141)
    at new _default (three-spritetext.module.js:128)

**Comment by etienne-martin** [comment]
Here's a repro (paste it in codesandbox):

```jsx
import React, { useState, useEffect } from "react";
import { ForceGraph3D } from "react-force-graph";
import SpriteText from "three-spritetext";
import "./styles.css";

export default function App() {
  const [user, setUser] = useState("etienne-martin");
  const [stars, setStars] = useState([]);

  useEffect(() => {
    (async () => {
      const res = await fetch(`https://api.github.com/users/${user}/starred`);

      setStars(await res.json());
    })();
  }, [user]);

  return (
    <div className="App">
      <h1>Hello CodeSandbox</h1>
      <h2>Start editing to see some magic happen!</h2>

      <ForceGraph3D
        graphData={{ nodes: stars, links: [] }}
        nodeAutoColorBy="group"
        nodeThreeObject={node => {
          const sprite = new SpriteText(node.id);

          sprite.color = node.color;
          sprite.textHeight = 8;
          return sprite;
        }}
      />
    </div>
  );
}
```

**Comment by vasturiano** [comment]
Thanks for that example @etienne-martin.

I see the issue. You're passing numbers to the library, i.e. in `new SpriteText(node.id)`, your `node.id` is a number not a string. Therefore internal string parsing breaks.
You can fix it immediately by coercing it to a string on input, for example: 
```new SpriteText(`${node.id}`)```

I'll also apply a patch to the lib to cater for this use case.
