### ISSUE TITLE
not working in Safari

### ISSUE THREAD

**Issue by mgiraldo** [vasturiano/three-spritetext#13]
I have it working in Chrome and Firefox (Mac OS Catalina 10.15.3) but it doesn't work in Safari. Getting system roman font instead.

**Comment by vasturiano** [comment]
@mgiraldo the example loads for me in Safari: https://vasturiano.github.io/three-spritetext/example/basic/
Does it not work for you?

**Comment by mgiraldo** [comment]
i mean it works but doesn't display the correct font. the same code works in firefox, chrome, and opera. i suppose safari requires a different name (but i tested many variations) or maybe that font doesn't work in safari.
