### ISSUE TITLE
Not working on Chromium without hardware acceleration

### ISSUE THREAD

**Issue by filippomc** [vasturiano/three-spritetext#16]
The sprite text does not work when hardware acceleration is not available on chromium.
The typical use case is virtualized enviroments, in which the outcome from the [d3-force-graph example ](https://vasturiano.github.io/3d-force-graph/example/text-nodes/)
![image](https://user-images.githubusercontent.com/46561561/87072322-d44dde80-c21b-11ea-95e9-3752614b274a.png).
The same problem does not appear on Firefox.

To replicate, simply disable hardware acceleration on Chrome/Chromium and open [this link](https://vasturiano.github.io/3d-force-graph/example/text-nodes/).

Not sure this is an issue with this library or d3 or Chromium itself . What I can see is other sprite-based features I'm aware of work with the same setup.

Thanks

**Comment by vasturiano** [comment]
@filippomc thanks for your report.

I looked a bit into it and it seems related to rendering of Sprites with hardware acceleration disabled.

This simple codepen example reproduces the issue:
https://codepen.io/vasturiano/pen/pogKjgo?editors=0010

The image sprite is invisible without hardware acceleration in Chrome. Firefox is fine as you've also verified.

I'm not quite sure why this is the case. Perhaps someone on the ThreeJS repo can shed a light on it.

**Comment by filippomc** [comment]
Thanks @vasturiano, will open an issue on the threejs repo.

**Comment by filippomc** [comment]
https://github.com/mrdoob/three.js/issues/19883

**Comment by filippomc** [comment]
@vasturiano the guys from threejs found the issue. Need to add a explicit parameter on scale for z.

So
```
this.scale.set(yScale * canvas.width / canvas.height, yScale, 0);
```

Rather than 
```
this.scale.set(yScale * canvas.width / canvas.height, yScale);
```
on line 147 of index.js (looks like I can't send a pr) solves the problem.

**Comment by vasturiano** [comment]
@filippomc ah fantastic. Would've been hard to spot! One would intuitively think that sprites don't need a z scale since they're 2D objects. 
I've issued a fix for it.

You mentioned you're not able to create a PR. Are you not able to fork this repo?

Thanks again for chasing this. 👍

**Comment by filippomc** [comment]
Yes it just seemed a overkill for this one line :) Thanks for issuing the fix.
