### ISSUE TITLE
Feature request: radius on background rectangle

### ISSUE THREAD

**Issue by EmilPoulsen** [vasturiano/three-spritetext#20]
Awesome library, exactly what I was looking for! Thanks @vasturiano!

It would be nice to have an option to set a radius to the background rectangle, similar to how Rhino3d does it with the dot objects (see picture below). Any clue on what the best approach would be to achieve this with the SpriteText @vasturiano? I'd happy to do look into it if I get a starting point.

Thanks!!

![image](https://user-images.githubusercontent.com/11620852/102575006-6f63b200-40f2-11eb-8a6a-f91d197415da.png)

**Comment by vasturiano** [comment]
@EmilPoulsen thanks for this nice suggestion.

I finally got around to implementing it. So, in the new `1.6.0` there is a `borderRadius` attribute that you can use for this purpose. 

It accepts either a single value for all corners symmetrically, or a separate value for each.

Let me know if it works for you.

**Comment by EmilPoulsen** [comment]
really sweet, excellent work @vasturiano. works like a charm! thanks
