### ISSUE TITLE
how to rotate the sprite text?

### ISSUE THREAD

**Issue by philxia** [vasturiano/three-spritetext#22]
Dear Vasco,

Is it possible to support sprite text rotation? Here is the case I want to support.
There are 2 texts when I draw a line. one for the angle, another for the line's length. I would like to rotate the length's text to align with the witness line.
I tried to fork a branch and set the texture.rotation but I sucked at the scale adjustment. Any idea? Thanks. 
![image](https://user-images.githubusercontent.com/2163604/111066018-d9280800-84f7-11eb-91ed-5861df111aee.png)

**Comment by vasturiano** [comment]
Hi @philxia, can you not achieve the same result by simply rotating the whole sprite object?
That can be done via the sprite material. So, something like:
```js
myTextSprite.material.rotation = Math.PI / 4;
```

**Comment by philxia** [comment]
I think the scale should be reset after the rotation is set. Here is what I got after only setting rotation.
![image](https://user-images.githubusercontent.com/2163604/111148919-2c1cc080-85c7-11eb-87ed-6f9f616a909b.png)

**Comment by philxia** [comment]
I tried to twist the scale a little but still not right.
`    const xScale = yScale * canvas.width / canvas.height;
    // this.scale.set(xScale, yScale, 0);
    const yScaleWithRotation = Math.cos(this._texture.rotation) * yScale + Math.sin(this._texture.rotation) * xScale;
    const xScaleWithRotation = Math.cos(this._texture.rotation) * xScale + Math.sin(this._texture.rotation) * yScale;
    this.scale.set(xScaleWithRotation, yScaleWithRotation, 0);`
![image](https://user-images.githubusercontent.com/2163604/111161419-182c8b00-85d6-11eb-8f56-eb9223fc7edb.png)

**Comment by vasturiano** [comment]
@philxia when I apply the rotation to the material I don't get the distortion you're showing.
Can you look at [this codepen](https://codepen.io/vasturiano/pen/XWNQMdX) and see if it's doing what you intend?

**Comment by philxia** [comment]
Good gravy! I rotated the texture instead of the material. Yes, it works perfectly. Thank you @vasturiano .
