### ISSUE TITLE
Can i set the background like div’s background ?

### ISSUE THREAD

**Issue by pxim** [vasturiano/three-spritetext#27]
like this：
`background: #00FF00 url(bgimage.gif) no-repeat fixed top;`

**Comment by vasturiano** [comment]
@pxim no, that's not currently supported in this module. But, you should be able to do that by overlapping with a separate sprite that includes the tiled background as you've described. You can make them both part of a [Group](https://threejs.org/docs/#api/en/objects/Group).

**Comment by pxim** [comment]
> @pxim no, that's not currently supported in this module. But, you should be able to do that by overlapping with a separate sprite that includes the tiled background as you've described. You can make them both part of a [Group](https://threejs.org/docs/#api/en/objects/Group).

I understand. Thank you very much
