### ISSUE TITLE
Add solid or semi-transparent background option

### ISSUE THREAD

**Issue by Public-Health-Bioinformatics** [vasturiano/three-spritetext#3]
Just a feature request to add an additional background color and transparency parameter that would enable text to stand out in a noisy environment. I presume this isn't too hard to do when generating sprite?

**Comment by vasturiano** [comment]
Thanks @Public-Health-Bioinformatics, that seems like a useful addition. I'll keep this issue open until I have a bit of time to add the functionality in. :)

**Comment by Public-Health-Bioinformatics** [comment]
Ok! Your project is greatly appreciated by me!  Last week I created http://genepio.org/ontotrek/index.html and was able to (temporarily) solve the "semi-transparent" background problem by injecting a 2nd sprite behind the text.  But having that be right in the text itself would be much better.
Cheers,
Damion

**Comment by Peque** [comment]
@vasturiano Any updates on this matter? :innocent:

**Comment by vasturiano** [comment]
Thanks for the reminder @Peque!

Following the css box model syntax, I've just added a few attributes that make this possible:
* backgroundColor
* padding
* borderWidth
* borderColor

See the [example](https://vasturiano.github.io/three-spritetext/example/basic/).

**Comment by Peque** [comment]
@vasturiano That is awesome. :heart_eyes: 

Thanks to you!
