### ISSUE TITLE
 "Raycaster.camera" needs to be set in order to raycast against sprites when used with react-force-graph

### ISSUE THREAD

**Issue by antonkulaga** [vasturiano/three-spritetext#31]
After updating to the latest dependencies I got:
```
 "Raycaster.camera" needs to be set in order to raycast against sprites
```
when using text sprites as nodes with react-foce-graph ForceGraphVR

**Comment by vasturiano** [comment]
@antonkulaga thanks for reaching out. This has been addressed in the other repo, where it is more relevant.
