### ISSUE TITLE
Text Expanding Issue

### ISSUE THREAD

**Issue by iantheearl** [vasturiano/three-spritetext#33]
Hi, thank you for this nice library!

I'm having issues changing the text to anything with a different length.
This is the original text:
![Screen Shot 2022-02-11 at 1 36 12 AM](https://user-images.githubusercontent.com/35216312/153553325-0d3d8653-5254-4bd0-b133-c69e797e5a99.png)

This is what happens when I set the `.text` property to `1231231231111` (longer):
![Screen Shot 2022-02-11 at 1 36 23 AM](https://user-images.githubusercontent.com/35216312/153553305-0f82c361-853d-40c9-9349-f986db4ed79a.png)

This is what happens when I set the text to `432` (shorter):
![image](https://user-images.githubusercontent.com/35216312/153553403-0a9735f8-16e7-4cc3-9a0b-fc616ed599c5.png)

What should I do to fix this? Am I missing any steps?

Thank you!

**Comment by vasturiano** [comment]
@iantheearl thanks for reaching out.

I've just fixed a bug with the inner Texture update that was likely the source of this issue. Could you please try with the latest version (`1.6.5`) to see if the problem is solved?

**Comment by iantheearl** [comment]
Thank you very much, the problem seems to have been solved 🙏
