### ISSUE TITLE
Custom Font Faces not working

### ISSUE THREAD

**Issue by dan-bizango** [vasturiano/three-spritetext#36]
When I try to use any custom font family that is imported or loaded with the sprite text, it reverts back to it's initial Arial font.
Is there any way to use a custom font face with the spriteText?

```
.nodeThreeObject(node => {
const sprite = new SpriteText(node.id);
sprite.material.depthWrite = true; // make sprite background transparent
sprite.color = colorScale(node.group/nodeCount);
sprite.background = "black";
sprite.fontFace = "tripper";
sprite.textHeight = 8;
return sprite;
 })
```

Thank you for your time on this!

**Comment by dan-bizango** [comment]
If anyone else needs help on this, I just ended up initially hiding the canvas, then update the nodes after the canvas gets drawn  and then fade in the canvas.

`        function updateNodes() {
            // Re-renders nodes so font-family will always load
            Graph.nodeThreeObject(function(node){
                const sprite = new SpriteText(node.id);
                sprite.fontFace = "tripper-new";
                sprite.color = colorScale(node.group/nodeCount);
                sprite.background = "black";
                sprite.textHeight = 9;
                return sprite;
            })
            $('canvas').addClass('active');
        }

        setTimeout(function(){
            updateNodes();
        },500);
`

**Comment by mneunomne** [comment]
thank you @dan-bizango your solution above worked for me. I was have same issue where the font usually was not loading in the first load of the webpage.
