### ISSUE TITLE
Constant text size

### ISSUE THREAD

**Issue by zzggyy1** [vasturiano/three-spritetext#4]
Is it possible to have the text labels at constant size regardless of the camera position? I tried sizeAttenuation false but the labels just become too big, covering the whole screen.

Thank you in advance!

**Comment by vasturiano** [comment]
@zzggyy1 I'm not aware of a way to do that. But would also like to know if it's possible somehow, so I'm open to ideas.
I suppose one could always scale the object at every movement of the camera to make sure the screen size remains constant regardless of the distance, but that seems quite brute-force.

**Comment by zzggyy1** [comment]
Thank you @vasturiano, for now I am doing the scale updating on camera movement like you suggested. Hopefully there will be a better solution.

**Comment by Peque** [comment]
Maybe useful/relevant links (sorry if not):

- https://threejs.org/examples/?q=label#css2d_label
- https://stemkoski.github.io/Three.js/Mouse-Tooltip.html

**Comment by vasturiano** [comment]
@Peque thanks for the references. I believe those are basically `div` elements overlayed on top of the canvas. So not `threejs` based. Is that the case?

**Comment by yunison** [comment]
`sizeAttenuation` of sprite material attribute may relate to this Issue.
[See this.](https://threejs.org/docs/?q=spriteMa#api/en/materials/SpriteMaterial.sizeAttenuation)

I adjust some settings using this.

```
const scaleDist = 0.001;
const spriteText = new SpriteText("your text", 5);
spriteText.material.sizeAttenuation = false;
spriteText.scale.set(spriteText.scale.x * scaleDist, spriteText.scale.y * scaleDist, 0);
```
