### ISSUE TITLE
Using three.js version >= 152 requires texture to specify "SRGBColorSpace"?

### ISSUE THREAD

**Issue by emirth** [vasturiano/three-spritetext#41]
Hello!

I believe the latest versions of ```three.js``` at time of writing, starting with version 152, will require the texture to have its ```colorSpace``` set to ```SRGBColorSpace.```   I'm not entirely sure why but believe it relates to changes introduced via [#25866](https://github.com/mrdoob/three.js/pull/25866).

The reason for my thinking this is that when I try the ```example/basic/index.html``` in this repository, changing ```ContainerText.backgroundColor``` from ```rgba(0,0,190,0.6)``` to ```rgba(55,71,79,1.0)```, I get this: 

![sprite-text-before](https://user-images.githubusercontent.com/85695145/235319905-67756ae4-c803-48d5-a5f5-a5c9242f0563.png)

When I then go into ```dist/three-spritetext.js``` source and add a new line specifying the ```colorSpace```:

```javascript
// Inject canvas into sprite
if (this.material.map) this.material.map.dispose(); // gc previous texture
var texture = this.material.map = new three.Texture(canvas);
texture.minFilter = three.LinearFilter;
texture.colorSpace = three.SRGBColorSpace;
```
I get the expected color:

![sprite-text-after](https://user-images.githubusercontent.com/85695145/235319906-4af520b0-ab2b-4da0-9f2a-6a77a1a26fa2.png)

And I also get the expected color if I change the ```<script/>``` tag that pulls in ```three.js``` to pull in some version less than 152.

**Comment by vasturiano** [comment]
Good catch @emirth, I was unaware of this change. Thanks.

I've updated the texture colorspace as you suggested, and recommended on https://threejs.org/docs/index.html#manual/en/introduction/Color-management.
