### ISSUE TITLE
Padding changes text size

### ISSUE THREAD

**Issue by surdu** [vasturiano/three-spritetext#52]
Hello,

If I add padding to a sprite, the size of the text changes.

Please see [this pen](https://codepen.io/surdu/pen/zxOYLrM) for an example.

The first two sprites should have the same text size, except the second one should have some padding around the text.

Also, setting the padding enforces a minimum text height. Note the third one has textHeight set to `0.001` yet it has almost the same text size as the second one with textHeight `3`

**Comment by vasturiano** [comment]
@surdu thanks for your report.

I've just pushed a fix that should solve your issue. There was interference by the padding / borders in the calculation of the textHeight which is now corrected. If you pull the latest version (`1.9.1`) the issue should be gone.
