### ISSUE TITLE
Type Inconsistency for "padding" Property

### ISSUE THREAD

**Issue by i-timur** [vasturiano/three-spritetext#54]
There is an inconsistency between the library's documentation and its current type definitions regarding the padding property. Documentation specifies that padding can accept a tuple of two numbers to define vertical and horizontal padding values separately. But current type definition only allows a single number to be passed, preventing the use of tuples as described in the documentation.

**Comment by vasturiano** [comment]
Thanks @i-timur! This has now been fixed in the latest version (`1.9.2`) that's just been released.
